config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :classrooms do
    resources :lessons, only: [ :new, :create, :edit, :update, :show, :delete ]
  end
  root "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_many :students, inverse_of: :classroom
    has_many :lessons, inverse_of: :classroom
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom, inverse_of: :lessons
  has_many :student_lessons, inverse_of: :lesson

  accepts_nested_attributes_for :student_lessons
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom, inverse_of: :students
  has_many :student_lessons, inverse_of: :student
end

app/models/student_lesson.rb
class StudentLesson < ApplicationRecord
  belongs_to :lesson, inverse_of: :student_lessons
  belongs_to :student, inverse_of: :student_lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[ show edit update destroy ]

  # GET /classrooms or /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1 or /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms or /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.turbo_stream
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully created." }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1 or /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully updated." }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1 or /classrooms/1.json
  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Classroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classroom_params
      params.require(:classroom).permit(:identification)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_classroom
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /classrooms/:classroom_id/lessons or /classrooms/:classroom_id/lessons.json
  def index
    @lessons = @classroom.lessons.all
  end

  # GET /classrooms/:classroom_id/lessons/1 or /classrooms/:classroom_id/lessons/1.json
  def show
  end

  # GET /classrooms/:classroom_id/lessons/new
  def new
    @lesson = @classroom.lessons.build
    @classroom.students.each do |student|
      rel = @lesson.student_lessons.build
      rel.student = student
    end
  end

  # GET /classrooms/:classroom_id/lessons/1/edit
  def edit
  end

  # POST /classrooms/:classroom_id/lessons or /classrooms/:classroom_id/lessons.json
  def create
    @lesson = @classroom.lessons.build(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to classroom_lesson_path(@classroom, @lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/:classroom_id/lessons/1 or /classrooms/:classroom_id/lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to classroom_lesson_path(@classroom, @lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/:classroom_id/lessons/1 or /classrooms/:classroom_id/lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to classroom_path(@classroom), notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:classroom_id])
    end
    def set_lesson
      @lesson = @classroom.lessons.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(
        :title, :description, :homework, :homework_link, :classroom_id,
        student_lessons_attributes: [ 
          :lesson_id, :student_id, 
          :abstract, :absent,
          :RC, :CP, :AG, :CM, :AP, :MV, :id
         ]
      )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :set_classrooms_list, only: %i[ new create edit update ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.turbo_stream
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_classrooms_list
      @classrooms = []
      Classroom.all.each do |c|
        @classrooms.append [ c.identification, c.id ]
      end
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:full_name, :responsible, :email, :birthdate, :username, :classroom_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_classroom.html.erb
<div id="<%= dom_id classroom %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Identification:</strong>
    <%= classroom.identification %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this classroom", classroom, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this classroom', edit_classroom_path(classroom), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom, class: "contents") do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
        <% classroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :identification %>
    <%= form.text_field :identification, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/classrooms/_lesson.html.erb
<div id="<%= lesson.id %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= lesson.title %>
  </p>

  <%= link_to "Show this lesson", classroom_lesson_path(classroon, lesson), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to 'Edit this lesson', edit_classroom_lesson_path(classroon, lesson), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
  <hr class="mt-6">
</div>

app/views/classrooms/create.turbo_stream.erb
<%= turbo_stream.prepend "classrooms" do %>
    <%= render @classroom %>
<% end %>

app/views/classrooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing classroom</h1>

  <%= render "form", classroom: @classroom %>

  <%= link_to "Show this classroom", @classroom, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to classrooms", classrooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/classrooms/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= turbo_frame_tag "new_classroom" do %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Classrooms</h1>
      <%= link_to 'New classroom', new_classroom_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>

  <div id="classrooms" class="min-w-full">
    <%= render @classrooms %>
  </div>
</div>

app/views/classrooms/new.html.erb
<%= turbo_frame_tag "new_classroom" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New classroom</h1>

    <%= render "form", classroom: @classroom %>

    <%= link_to 'Back to classrooms', classrooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/classrooms/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= link_to 'New Lesson', new_classroom_lesson_path(@classroom), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <%= render @classroom %>

    <% @classroom.lessons.each do |lesson| %>
    <div id="lessons" class="min-w-full grid grid-cols-3 gap-8">
      <%= render partial: "lesson", locals: { classroon: @classroom, lesson: lesson }  %>
    </div>
    <% end %>

    <div class="block">
      <%= link_to 'Edit this classroom', edit_classroom_path(@classroom), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this classroom', classroom_path(@classroom), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to 'Back to classrooms', classrooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaAulas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="flex justify-center space-x-4">
      <%= link_to "Home", root_path, class:"font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900" %>
      <%= link_to "Classrooms", classrooms_path, class:"font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900" %>
      <%= link_to "Students", students_path, class:"font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900" %>
    </nav>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lessons/_form.html.erb
<%
  url = ""
  if action_name == "edit"
    url = classroom_lesson_path(@classroom, lesson)
  else
    url = classroom_lessons_path(@classroom, lesson)
  end
%>
<h1> <%= url %> </h1>
<%= form_with(model: lesson, url: url, class: "contents") do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :homework %>
    <%= form.text_area :homework, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :homework_link %>
    <%= form.text_field :homework_link, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :classroom_id %>
    <%= form.text_field :classroom_name, value: form.object.classroom.identification, disabled: true , class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <%= form.hidden_field :classroom_id %>
  </div>

  <div class="w-full">
    <%= form.fields_for :student_lessons do |field| %>

      <%= field.hidden_field :lesson_id %>
      <%= field.hidden_field :student_id %>

      <div class="my-5">
        <%= field.label :student_id %>
        <%= field.text_field :student_name, value: field.object.student.full_name, disabled: true , class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="my-5">
        <%= field.label :absent %>
        <%= field.check_box :absent, class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" %>
      </div>
      <div class="my-5">
        <%= field.label :abstract %>
        <%= field.text_area :abstract, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="grid grid-cols-3">
        <div class="my-5">
          <%= field.label :RC %>
          <%= field.number_field :RC, in: 1..5, step: 1, value: field.object.RC ? field.object.RC : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
        <div class="my-5">
          <%= field.label :CP %>
          <%= field.number_field :CP, in: 1..5, step: 1, value: field.object.CP ? field.object.CP : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
        <div class="my-5">
          <%= field.label :AG %>
          <%= field.number_field :AG, in: 1..5, step: 1, value: field.object.AG ? field.object.AG : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
        <div class="my-5">
          <%= field.label :CM %>
          <%= field.number_field :CM, in: 1..5, step: 1, value: field.object.CM ? field.object.CM : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
        <div class="my-5">
          <%= field.label :AP %>
          <%= field.number_field :AP, in: 1..5, step: 1, value: field.object.AP ? field.object.AP : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
        <div class="my-5">
          <%= field.label :MV %>
          <%= field.number_field :MV, in: 1..5, step: 1, value: field.object.MV ? field.object.MV : 1 , class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= lesson.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lesson.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Homework:</strong>
    <%= lesson.homework %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Homework_link:</strong>
    <%= lesson.homework_link %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Classroom:</strong>
    <%= lesson.classroom_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this lesson", classroom_lesson_path(@classroom, lesson), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to 'Edit this lesson', edit_classroom_lesson_path(@classroom, lesson), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/lessons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Show this lesson", edit_classroom_lesson_path(@lesson), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lessons", classroom_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lessons</h1>
    <%= link_to 'New lesson', new_classroom_lesson_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lessons" class="min-w-full">
    <%= render @lessons %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to 'Back to lessons', classroom_lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lesson %>

    <%= link_to 'Edit this lesson', edit_classroom_lesson_path(@classroom, @lesson), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this lesson', classroom_lesson_path(@classroom, @lesson), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to Classroom', classroom_path(@classroom), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/pages/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#index</h1>
  <p>Find me in app/views/pages/index.html.erb</p>
</div>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>" class="break-inside-avoid">
  <p class="my-5">
    <strong class="block font-medium mb-1">Full name:</strong>
    <%= student.full_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Responsible:</strong>
    <%= student.responsible %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= student.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Birthdate:</strong>
    <%= student.birthdate %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Username:</strong>
    <%= student.username %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Classroom:</strong>
    <%= student.classroom_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this student", student, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this student', edit_student_path(student), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/students/create.turbo_stream.erb
<%= turbo_stream.prepend "students" do %>
    <%= render @student %>
<% end %>

app/views/students/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing student</h1>

  <%= render "form", student: @student %>

  <%= link_to "Show this student", @student, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to students", students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/students/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= turbo_frame_tag "new_student" do %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Students</h1>
      <%= link_to 'New student', new_student_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>

  <div id="students" class="min-w-full grid grid-cols-3">
    <%= render @students %>
  </div>
</div>

app/views/students/new.html.erb
<%= turbo_frame_tag "new_student" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New student</h1>

    <%= render "form", student: @student %>

    <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/students/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @student %>

    <%= link_to 'Edit this student', edit_student_path(@student), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this student', student_path(@student), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>